/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Doctor;
import BLL.Login;
import BLL.Patient;
import DAL.DoctorRepository;
import DAL.HealthException;
import DAL.LoginRepository;
import DAL.PatientRepository;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enis
 */
public class MySettingsFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MySettingsFrame
     */
    public MySettingsFrame() {
        initComponents();
    }

    private int roli;
    private int patientID_Table;

    public void setPatientIDTable(int ptd) {
        this.patientID_Table = ptd;
    }

    public int getPatientIDTable() {
        return patientID_Table;
    }

    private int doctor_ID_Profile;

    public int getDoctorIDProfile(int dtd) {
        return doctor_ID_Profile = dtd;
    }

    public void setDoctorIDProfile(int doctorID) {
        this.doctor_ID_Profile = doctorID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editNameLabel = new javax.swing.JLabel();
        editEmailAddressLabel = new javax.swing.JLabel();
        editPhoneNrLabel = new javax.swing.JLabel();
        editSexLabel = new javax.swing.JLabel();
        editAddressLabel = new javax.swing.JLabel();
        editPasswordLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JTextField();
        emailLabel = new javax.swing.JTextField();
        phoneNrLabel = new javax.swing.JTextField();
        sexLabel = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JPasswordField();

        setClosable(true);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(842, 548));
        setMinimumSize(new java.awt.Dimension(842, 548));
        setPreferredSize(new java.awt.Dimension(842, 548));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(15544, 454545));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(0, 168, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" General Account Settings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/patient.png"))); // NOI18N

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText(" Name:");
        jLabel3.setOpaque(true);

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText(" Email Address:");
        jLabel5.setOpaque(true);

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText(" Phone Nr. :");
        jLabel7.setOpaque(true);

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText(" Sex :");
        jLabel9.setOpaque(true);

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText(" Address :");
        jLabel11.setOpaque(true);

        jLabel1.setBackground(Color.LIGHT_GRAY);
        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText(" Password");
        jLabel13.setOpaque(true);

        editNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editNameLabel.setForeground(new java.awt.Color(25, 42, 86));
        editNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editNameLabel.setText("Edit");
        editNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editNameLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editNameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editNameLabelMouseExited(evt);
            }
        });

        editEmailAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editEmailAddressLabel.setForeground(new java.awt.Color(25, 42, 86));
        editEmailAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editEmailAddressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editEmailAddressLabel.setText("Edit");
        editEmailAddressLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editEmailAddressLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEmailAddressLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editEmailAddressLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editEmailAddressLabelMouseExited(evt);
            }
        });

        editPhoneNrLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editPhoneNrLabel.setForeground(new java.awt.Color(25, 42, 86));
        editPhoneNrLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editPhoneNrLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editPhoneNrLabel.setText("Edit");
        editPhoneNrLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPhoneNrLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPhoneNrLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPhoneNrLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPhoneNrLabelMouseExited(evt);
            }
        });

        editSexLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editSexLabel.setForeground(new java.awt.Color(25, 42, 86));
        editSexLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editSexLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editSexLabel.setText("Edit");
        editSexLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSexLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSexLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editSexLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editSexLabelMouseExited(evt);
            }
        });

        editAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editAddressLabel.setForeground(new java.awt.Color(25, 42, 86));
        editAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editAddressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editAddressLabel.setText("Edit");
        editAddressLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editAddressLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editAddressLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editAddressLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editAddressLabelMouseExited(evt);
            }
        });

        editPasswordLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editPasswordLabel.setForeground(new java.awt.Color(25, 42, 86));
        editPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        editPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/pencil.png"))); // NOI18N
        editPasswordLabel.setText("Edit");
        editPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPasswordLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPasswordLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPasswordLabelMouseExited(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/ButtonBackground/ConfirmButton.png"))); // NOI18N
        updateButton.setText("   Update");
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/confirmButton.png"))); // NOI18N
        updateButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/confirmButton.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/ButtonBackground/cancelButton.png"))); // NOI18N
        cancelButton.setText("   Cancel");
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/cancelButtonHover.png"))); // NOI18N
        cancelButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/cancelButtonHover.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nameLabel.setEditable(false);

        emailLabel.setEditable(false);

        phoneNrLabel.setEditable(false);

        sexLabel.setEditable(false);

        AddressLabel.setEditable(false);

        passwordLabel.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(619, 619, 619))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(editNameLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editAddressLabel)
                                    .addComponent(editEmailAddressLabel)
                                    .addComponent(editPhoneNrLabel)
                                    .addComponent(editSexLabel)
                                    .addComponent(editPasswordLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(529, 529, 529))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editNameLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editEmailAddressLabel)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPhoneNrLabel)
                            .addComponent(phoneNrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSexLabel)
                    .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAddressLabel)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPasswordLabel)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadLabelsForPatient() {
        try {
            Patient p = new PatientRepository().findByID(this.patientID_Table);
            nameLabel.setText(p.getFirstName() + " " + p.getLastName());
            emailLabel.setText(p.getEmail());
            phoneNrLabel.setText(p.getPhoneNumber());
            sexLabel.setText(p.getSex());
            AddressLabel.setText(p.getAddress());
            passwordLabel.setText(p.getPassword());
            roli = 3;
        } catch (HealthException ex) {
            Logger.getLogger(MySettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadLabelsForDoctor() {
        try {
            Doctor p = new DoctorRepository().findByID(this.doctor_ID_Profile);
            nameLabel.setText(p.getFirstName() + " " + p.getLastName());
            emailLabel.setText(p.getEmail());
            phoneNrLabel.setText(p.getPhoneNumber());
            sexLabel.setText(p.getSex());
            AddressLabel.setText(p.getAddress());
            passwordLabel.setText(p.getPassword());
            roli = 2;
        } catch (HealthException ex) {
            Logger.getLogger(MySettingsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void editNameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editNameLabelMouseEntered
        Font font = editNameLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editNameLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editNameLabelMouseEntered

    private void editNameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editNameLabelMouseExited
        editNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editNameLabelMouseExited

    private void editEmailAddressLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmailAddressLabelMouseEntered
        Font font = editEmailAddressLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editEmailAddressLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editEmailAddressLabelMouseEntered

    private void editEmailAddressLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmailAddressLabelMouseExited
        editEmailAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editEmailAddressLabelMouseExited

    private void editPhoneNrLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPhoneNrLabelMouseEntered
        Font font = editPhoneNrLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editPhoneNrLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editPhoneNrLabelMouseEntered

    private void editPhoneNrLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPhoneNrLabelMouseExited
        editPhoneNrLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editPhoneNrLabelMouseExited

    private void editSexLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSexLabelMouseEntered
        Font font = editSexLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editSexLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editSexLabelMouseEntered

    private void editSexLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSexLabelMouseExited
        editSexLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editSexLabelMouseExited

    private void editAddressLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAddressLabelMouseEntered
        Font font = editAddressLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editAddressLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editAddressLabelMouseEntered

    private void editAddressLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAddressLabelMouseExited
        editAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editAddressLabelMouseExited

    private void editPasswordLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPasswordLabelMouseEntered
        Font font = editPasswordLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        editPasswordLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_editPasswordLabelMouseEntered

    private void editPasswordLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPasswordLabelMouseExited
        editPasswordLabel.setFont(new java.awt.Font("Times New Roman", 0, 16));
    }//GEN-LAST:event_editPasswordLabelMouseExited

    public void checkForEmptySpaces() throws HealthException {
        if (nameLabel.getText().trim().isEmpty() || emailLabel.getText().trim().isEmpty() || phoneNrLabel.getText().trim().isEmpty() || sexLabel.getText().trim().isEmpty()
                || AddressLabel.getText().trim().isEmpty() || (new String(passwordLabel.getPassword())).trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "White Spaces not accepted !");
            throw new HealthException("Hapesira te zbrazeta ");
        }
    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (this.roli == 2) {
            try {
                checkForEmptySpaces();
                DoctorRepository dr = new DoctorRepository();
                Doctor p = dr.findByID(this.doctor_ID_Profile);
                String[] name = nameLabel.getText().split(" ");
                p.setFirstName(name[0]);
                p.setLastName(name[1]);
                p.setEmail(emailLabel.getText());
                p.setPhoneNumber(phoneNrLabel.getText());
                p.setSex(sexLabel.getText());
                p.setAddress(AddressLabel.getText());
                p.setPassword(new String(passwordLabel.getPassword()));
                dr.edit(p);
                LoginRepository lr = new LoginRepository();
                Login l = lr.findByID(p.getLoginID().getLoginID());
                l.setPassword(new String(passwordLabel.getPassword()));
                lr.edit(l);
                this.dispose();
                JOptionPane.showMessageDialog(this, "Changes are saved");
            } catch (HealthException ex) {
                
            } catch (NullPointerException ex) {
                
            }

        } else if (this.roli == 3) {
            try {
                checkForEmptySpaces();
                PatientRepository dr = new PatientRepository();
                Patient p = dr.findByID(this.patientID_Table);
                String[] name = nameLabel.getText().split(" ");
                p.setFirstName(name[0]);
                if (name.length == 1) {
                    JOptionPane.showMessageDialog(this,"U need to write an surname too!");
                    throw new HealthException("BOI!");
                }
                p.setLastName(name[1]);
                p.setEmail(emailLabel.getText());
                p.setPhoneNumber(phoneNrLabel.getText());
                p.setSex(sexLabel.getText());
                p.setAddress(AddressLabel.getText());
                p.setPassword(new String(passwordLabel.getPassword()));
                dr.edit(p);
                LoginRepository lr = new LoginRepository();
                Login l = lr.findByID(p.getLoginId().getLoginID());
                l.setPassword(new String(passwordLabel.getPassword()));
                lr.edit(l);
                this.dispose();
                JOptionPane.showMessageDialog(this, "Changes are saved,please restart the application !");
            } catch (HealthException ex) {
            }
        }
       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void editNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editNameLabelMouseClicked
        // TODO add your handling code here:
        nameLabel.setEditable(true);
    }//GEN-LAST:event_editNameLabelMouseClicked

    private void editEmailAddressLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmailAddressLabelMouseClicked
        // TODO add your handling code here:
        emailLabel.setEditable(true);
    }//GEN-LAST:event_editEmailAddressLabelMouseClicked

    private void editPhoneNrLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPhoneNrLabelMouseClicked
        // TODO add your handling code here:
        phoneNrLabel.setEditable(true);
    }//GEN-LAST:event_editPhoneNrLabelMouseClicked

    private void editSexLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSexLabelMouseClicked
        // TODO add your handling code here:
        sexLabel.setEditable(true);
    }//GEN-LAST:event_editSexLabelMouseClicked

    private void editAddressLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAddressLabelMouseClicked
        // TODO add your handling code here:
        AddressLabel.setEditable(true);
    }//GEN-LAST:event_editAddressLabelMouseClicked

    private void editPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPasswordLabelMouseClicked
        // TODO add your handling code here:
        passwordLabel.setEditable(true);
    }//GEN-LAST:event_editPasswordLabelMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(this, "You canceled you re changes");
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel editAddressLabel;
    private javax.swing.JLabel editEmailAddressLabel;
    private javax.swing.JLabel editNameLabel;
    private javax.swing.JLabel editPasswordLabel;
    private javax.swing.JLabel editPhoneNrLabel;
    private javax.swing.JLabel editSexLabel;
    private javax.swing.JTextField emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameLabel;
    private javax.swing.JPasswordField passwordLabel;
    private javax.swing.JTextField phoneNrLabel;
    private javax.swing.JTextField sexLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
