/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View.Admin;

import BLL.Doctor;
import BLL.Login;
import BLL.Patient;
import DAL.DoctorRepository;
import DAL.HealthException;
import DAL.LoginRepository;
import DAL.PatientRepository;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Enis
 */
public class AddDoctorFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddDoctorFrame
     */
    public AddDoctorFrame() {
        initComponents();
        setVisible(true);
    }

    private int PatientOrDoctor;

    public void setPatientOrDoctor(int i) {
        this.PatientOrDoctor = i;
    }

    public int getPatientOrDoctor() {
        return PatientOrDoctor;
    }

    public JLabel getSpecializationLabel() {
        return specializationLabel;
    }

    public void setSpecializationLabel(JLabel specializationLabel) {
        this.specializationLabel = specializationLabel;
    }

    public JTextField getSpecializationText() {
        return specializationText;
    }

    public void setSpecializationText(JTextField specializationText) {
        this.specializationText = specializationText;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    public Date setTime(Calendar c) throws ParseException {
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String now = dateformat.format(c.getTime());
        return new SimpleDateFormat("yyyy-MM-dd").parse(now);
    }

    public String turnPasswordFieldToString(JPasswordField passwordField) {
        char[] chars = passwordField.getPassword();
        String a = "";
        for (int i = 0; i < chars.length; i++) {
            a += "" + chars[i];
        }
        return a;
    }

    public boolean annyIsEmpty() {
        if (usernameText.getText().trim().isEmpty() || FirstNameText.getText().trim().isEmpty() || lastNameText.getText().trim().isEmpty() || passwordText.getPassword().equals("") || emailText.getText().trim().isEmpty()
                || repeatPasswordText.getPassword().equals("") || addressText.getText().trim().isEmpty() || phoneNrText.getText().trim().isEmpty() || specializationText.getText().trim().isEmpty()) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        specializationLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        specializationText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        repeatedLabelPassword = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        repeatPasswordText = new javax.swing.JPasswordField();
        firstNameLabel6 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        dateOfBirthLabel = new javax.swing.JLabel();
        dateChooser = new datechooser.beans.DateChooserCombo();
        sexLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        phoneNrLabel = new javax.swing.JLabel();
        phoneNrText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(842, 602));
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(0, 168, 255));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText(" Doctor Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons Folder/patient.png"))); // NOI18N

        titleLabel.setBackground(Color.LIGHT_GRAY);
        firstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstNameLabel.setText(" First Name:");
        firstNameLabel.setOpaque(true);

        FirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextActionPerformed(evt);
            }
        });

        titleLabel.setBackground(Color.LIGHT_GRAY);
        specializationLabel.setBackground(new java.awt.Color(255, 255, 255));
        specializationLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        specializationLabel.setText(" Specialization:");
        specializationLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        lastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastNameLabel.setText(" Last Name:");
        lastNameLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernameLabel.setText(" Username:");
        usernameLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordLabel.setText(" Password:");
        passwordLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        repeatedLabelPassword.setBackground(new java.awt.Color(255, 255, 255));
        repeatedLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        repeatedLabelPassword.setText(" Repeat Password:");
        repeatedLabelPassword.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        firstNameLabel6.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstNameLabel6.setText(" Email:");
        firstNameLabel6.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        dateOfBirthLabel.setBackground(new java.awt.Color(255, 255, 255));
        dateOfBirthLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateOfBirthLabel.setText("Date Of Birth: ");
        dateOfBirthLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        sexLabel.setBackground(new java.awt.Color(255, 255, 255));
        sexLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sexLabel.setText("Sex :");
        sexLabel.setOpaque(true);

        maleButton.setBackground(new java.awt.Color(255, 255, 255));
        maleButton.setText("Male");

        femaleButton.setBackground(new java.awt.Color(255, 255, 255));
        femaleButton.setText("Female");

        titleLabel.setBackground(Color.LIGHT_GRAY);
        addressLabel.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addressLabel.setText("Address: ");
        addressLabel.setOpaque(true);

        titleLabel.setBackground(Color.LIGHT_GRAY);
        phoneNrLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneNrLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phoneNrLabel.setText("Phone Nr. :");
        phoneNrLabel.setOpaque(true);

        updateButton.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/ButtonBackground/ConfirmButton.png"))); // NOI18N
        updateButton.setText("Create");
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/confirmButton.png"))); // NOI18N
        updateButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/confirmButton.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/ButtonBackground/cancelButton.png"))); // NOI18N
        cancelButton.setText("   Cancel");
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/cancelButtonHover.png"))); // NOI18N
        cancelButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonsFolder/Clicked/cancelButtonHover.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(profileLabel)
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(maleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(femaleButton))
                            .addComponent(addressLabel))
                        .addContainerGap(401, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneNrText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(specializationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(specializationText)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(dateOfBirthLabel)
                            .addComponent(phoneNrLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameLabel)
                                    .addComponent(usernameText)
                                    .addComponent(passwordLabel)
                                    .addComponent(repeatedLabelPassword)
                                    .addComponent(passwordText)
                                    .addComponent(repeatPasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profileLabel)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specializationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specializationText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(passwordText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatedLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleButton)
                            .addComponent(femaleButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(phoneNrText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (PatientOrDoctor == 2) {
            Login l = new Login();
            LoginRepository lr = new LoginRepository();
            Doctor d = new Doctor();
            DoctorRepository dr = new DoctorRepository();

            d.setFirstName(FirstNameText.getText());
            d.setLastName(lastNameText.getText());
            d.setSpecalization(specializationText.getText());
            d.setEmail(emailText.getText());
            d.setAddress(addressText.getText());
            try {
                d.setDateOfBirth(setTime(dateChooser.getCurrent()));
            } catch (ParseException ex) {
                Logger.getLogger(AddDoctorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (maleButton.isSelected()) {
                d.setSex("Male");
            } else if (femaleButton.isSelected()) {
                d.setSex("Female");
            } else {
                JOptionPane.showMessageDialog(this, "Gender is not selected");
            }
            d.setPhoneNumber(phoneNrText.getText());
            try {
                d.setUsername(usernameText.getText());
                l.setUsername(usernameText.getText());
                if (!turnPasswordFieldToString(passwordText).equalsIgnoreCase(turnPasswordFieldToString(repeatPasswordText))) {
                    JOptionPane.showMessageDialog(this, "Passwords dont match !");
                    passwordText.setText("");
                    repeatPasswordText.setText("");
                } else {
                    d.setPassword(new String(passwordText.getPassword()));
                    l.setPassword(new String(passwordText.getPassword()));
                }
                l.setRoli(2);
                lr.create(l);
                d.setLoginID(l);
                if (annyIsEmpty()) {
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "You ve not registered succesfully!");
                } else {
                    dr.create(d);
                    this.dispose();
                }
            } catch (HealthException ex) {
                Logger.getLogger(AddDoctorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (PatientOrDoctor == 3) {
            Login l = new Login();
            LoginRepository lr = new LoginRepository();
            Patient d = new Patient();
            PatientRepository dr = new PatientRepository();

            d.setFirstName(FirstNameText.getText());
            d.setLastName(lastNameText.getText());
            d.setParentName(specializationText.getText());
            d.setEmail(emailText.getText());
            d.setAddress(addressText.getText());
            try {
                d.setDateOfBirth(setTime(dateChooser.getCurrent()));
            } catch (ParseException ex) {
                Logger.getLogger(AddDoctorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (maleButton.isSelected()) {
                d.setSex("Male");
            } else if (femaleButton.isSelected()) {
                d.setSex("Female");
            } else {
                JOptionPane.showMessageDialog(this, "Gender is not selected");
            }
            d.setPhoneNumber(phoneNrText.getText());
            try {
                d.setUsername(usernameText.getText());
                l.setUsername(usernameText.getText());
                if (!turnPasswordFieldToString(passwordText).equalsIgnoreCase(turnPasswordFieldToString(repeatPasswordText))) {
                    JOptionPane.showMessageDialog(this, "Passwords dont match !");
                    passwordText.setText("");
                    repeatPasswordText.setText("");
                } else {
                    d.setPassword(new String(passwordText.getPassword()));
                    l.setPassword(new String(passwordText.getPassword()));
                }
                l.setRoli(3);
                lr.create(l);
                d.setLoginId(l);
                if (annyIsEmpty()) {
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "You ve not registered succesfully!");
                } else {
                    dr.create(d);
                    this.dispose();
                }
            } catch (HealthException ex) {
                Logger.getLogger(AddDoctorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Can not define if it s a doctor or patient.");
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void FirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FirstNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddDoctorFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton cancelButton;
    private datechooser.beans.DateChooserCombo dateChooser;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel phoneNrLabel;
    private javax.swing.JTextField phoneNrText;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPasswordField repeatPasswordText;
    private javax.swing.JLabel repeatedLabelPassword;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel specializationLabel;
    private javax.swing.JTextField specializationText;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
